// This file is automatically generated.
export const firebaseConfig = {
  apiKey: "AIzaSyCGogDfRjhici8W8GUj_Am4gLZQ8m_mE9I",
  authDomain: "studio-4323047130-bec1c.firebaseapp.com",
  projectId: "studio-4323047130-bec1c",
  storageBucket: "studio-4323047130-bec1c.appspot.com",
  messagingSenderId: "1058881747109",
  appId: "1:1058881747109:web:5a320e3767fa01d62ff54c",
  measurementId: ""
};
